# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate latest release and publish jar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew setupCiWorkspace build
    - name: Upload jar as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Jar file
        path: build/libs/*.jar
    - name: Create release from new jar
      uses: softprops/action-gh-release@v0.1.7
      with:
        files: build/libs/*.jar